# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-14 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('event_url', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('poster_url', models.CharField(max_length=255)),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_google_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lineup',
            name='show_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Show'),
        ),
    ]
