# Generated by Django 2.2.3 on 2019-07-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='venue_google_id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='venue_name',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='show_id',
        ),
        migrations.AddField(
            model_name='show',
            name='venue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='google_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='lat',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='long',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
