# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-14 21:39
from __future__ import unicode_literals

from django.db import migrations

def combine_names(api, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Show = api.get_model('api', 'Show')
    for show in Show.objects.all():
        show.name = 'Show Name'
        show.description = 'Show Description'
        show.event_url = 'URL'
        show.date = '2019-07-14 15:16:38.643787'
        show.poster_url = 'poster urls'
        show.venue_name = "venue name"
        show.venue_google_id = '12345'
        show.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
    ]
