# Generated by Django 2.2.3 on 2019-07-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190716_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='google_id',
            field=models.CharField(max_length=255),
        ),
    ]
